const mockReviews = [
  {
    name: "John Doe",
    rating: 5,
    title: "Amazing cookie!",
    content: "This is the best cookie I’ve ever had.",
    photo: "/cookie.jpg",
    likes: 3,
    dislikes: 0,
    date: "2024-01-13",
  },
  
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },

  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",

    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },

  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",

    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },

  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
  {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  },
    {
    name: "Jane Smith",
    rating: 4,
    title: "Very tasty",
    content: "Not perfect, but really good.",
    photo: "/cookie.jpg",
    likes: 2,
    dislikes: 1,
    date: "2024-01-12",
  }
];

export default mockReviews;
